### ISSUE TITLE
JFreeChart ChartPanel renders as Raster rather than Vector

### ISSUE THREAD

**Issue by Ayilay** [jfree/orsonpdf#3]
In OrsonPDF Version 1.7 (downloaded from [Object Refinery](http://www.object-refinery.com/orsonpdf/) ), I tried to run the demo programs (under src/main/java/com/orsonpdf/demo) to verify that JFreeCharts indeed render as vector format pdfs.

PDFBarChartDemo1 seems to render a very beautiful PDF, so what I did is I copied the `createChart()` and `createDataset()` methods from it and put them in SwingUIToPDFDemo. Then I modified the `createContent()` method, and changed the following line:

>  tabs.add("Tab 2", new JButton("Second Tab"));

to look as follows:

>  tabs.add("Tab 2", new ChartPanel(createChart(createDataset())));

When I run the SwingUIToPDFDemo now, on Tab 2 I get the same JFreeChart as I got when running the Bar Chart demo, yet when I press the "Save to PDF" button, the pdf that I get renders the chart as a raster chart rather than a vector chart.

Is there a workaround for this?

**Comment by Ayilay** [comment]
I found a workaround for this, it's kinda hacky but I've tested it and it works great.

I'm extending my ChartPanel with an anonymous class (I could make an actual class if I had to make many of these, or make a Factory), and I'm overwriting the paintComponent method such that if an instance of PDFGraphics2D is passed in, it uses JFreeChart's `draw()` method to draw a vector-graphics object, otherwise it uses the default `super.paintComponent()`

Here is what that looks like:

    
    JFreeChart someChart = /* some init code */;
    ChartPanel chartPanel = new ChartPanel(someChart) {
        @Override
        public void paintComponent(Graphics g) {
            if (g instanceof PDFGraphics2D) {
                // This is invoked if we are trying to print this
                // ChartPanel to a PDF (print in vector format)
                this.getChart().draw((PDFGraphics2D) g, getBounds());
            }
            else {
                // This is invoked if the regular GUI is trying to
                // display this ChartPanel (default behaviour)
                super.paintComponent(g);
            }
        }
    };

Is there a better place to share this solution than this issue-tracker on GitHub?

**Comment by jfree** [comment]
When you create the ChartPanel, there is another constructor where you can specify if you want buffering in the panel (to an offscreen BufferedImage).  If you pass false for this parameter, you should get vector output in the PDF.  Then you won't need your subclass.
