### ISSUE TITLE
Transformation (scaling) issue after g2.create()

### ISSUE THREAD

**Issue by qwert2003** [jfree/orsonpdf#4]
After calling `Graphics2D tempGraphics = (Graphics2D) g2d.create();` and doing transformations on the tempGraphics object (see method code below), there is some unexpected behaviour.
When drawing again on the original g2d object, the drawing is done at wrong scale (and place).

In other words: the "Transform" of the original Graphics2D object gets changed by its copy.

```
   private void drawString(Graphics2D g2d, String lb, double mmX, double mmY) {
        float sf = 10; //fontscalefactor
        AffineTransform scaled = AffineTransform.getScaleInstance(1d / sf, 1d / sf);
        Graphics2D tempGraphics = (Graphics2D) g2d.create();
        tempGraphics.transform(scaled);
        tempGraphics.drawString(lb, (float)mmX * sf, (float)mmY * sf);
        tempGraphics.dispose(); // Release system ressources
    }
```

It seems that PDFGraphics2D.create() passes over the GraphicsStream object gs to the new Graphics object. So the original and new Graphics objects share gs. Maybe this is the reason transformations apply to both objects.

Note: jFreeSvg does not have this issue

**Comment by jfree** [comment]
Thanks for the report.  It's a while since I worked on the code, but I recall the transformation stuff was quite hard to get working.  A good first step will be to add a test case to TestGraphics2D.java, to highlight this case.  Hopefully I'll find some time soon.

**Comment by qwert2003** [comment]
I have added a test to TestGraphics2D.java. It completes successfully.

```    
    /**
     * https://github.com/jfree/orsonpdf/issues/4
     */
    @Test
    public void checkCreate_and_transform() {
        g2.scale(72d/25.4d, 72d/25.4d);
        AffineTransform torig = g2.getTransform();
        
        float sf = 10; //fontscalefactor
        AffineTransform scaled = AffineTransform.getScaleInstance(1d / sf, 1d / sf);
        Graphics2D tempGraphics = (Graphics2D) g2.create();
        assertEquals(tempGraphics.getTransform(), g2.getTransform());
        tempGraphics.transform(scaled);
        tempGraphics.drawString("Label", 15f * sf, 15f * sf);
        AffineTransform ttemp = tempGraphics.getTransform();
        assertNotEquals(ttemp, g2.getTransform());
        tempGraphics.dispose(); // Release system ressources
        
        assertNotEquals(ttemp, g2.getTransform());
        assertEquals(torig, g2.getTransform());
    }
```
Then I've written a test class Example.java. It does some drawing on a "sheet 150 x 100 mm", once rendering to png and once to pdf (using orsonpdf). The red line is not as expected in the pdf.

[Example.java.txt](https://github.com/jfree/orsonpdf/files/2593451/Example.java.txt)
![output](https://user-images.githubusercontent.com/13591316/48680753-52202a80-eb9e-11e8-9663-f2aac651b07b.png)
[output.pdf](https://github.com/jfree/orsonpdf/files/2593452/output.pdf)

**Comment by qwert2003** [comment]
It seems that PDFGraphics2D does pass over all the transformations to the pdf. E.g. when scaling it writes `10 0 0 10 0 0 cm` into the pdf stream. For the main graphics context that works fine. 
However when new graphics objects are created, I guess the transformations should be applied internally (within orsonpdf) and the pdf transformation state should not be changed. This could be achieved in the method _draw(Shape s)_ using `if (!transform.isIdentity()) {s = transform.createTransformedShape(s);}`

First I had tried to write a quick work around. The method _dispose()_ reverts the transformations (full diff attached). While it works for some java2d code (as in the example above), it is clearly not a general solution to the issue.
```
@Override
     public void dispose() {
-        // nothing to do
+        if (initialTransform == null) {
+            return; // nothing to do
+        }
+        // reset the pdf-transformation to the initial state
+        // TODO: current solution relies on the assuption, 
+        //       that the graphic state has not been changed by other instances.
+        AffineTransform tt = new AffineTransform(getTransform());
+        try {
+            AffineTransform comb = tt.createInverse();
+            comb.concatenate(initialTransform);
+            if (!comb.isIdentity()) transform(comb);
+        } catch (NoninvertibleTransformException e) {
+          // do nothing
+        }
     }
```

[workaround.diff.txt](https://github.com/jfree/orsonpdf/files/2684025/workaround.diff.txt)

**Comment by jfree** [comment]
You are right about the shared GraphicsStream being the source of the issue.  I have applied a workaround along the lines of what you suggested, it will work for any temporary Graphics2D instance that is created, used and disposed immediately, as long as no other transform changes are made either via the parent Graphics2D or other temporary instances created via the create() method.

I think that would be the case for the majority of real world cases, but let's see.
